"""Add topic column to chats

Revision ID: 4a46ace7f3df
Revises: 1ef207923052
Create Date: 2025-07-22 11:37:42.937949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a46ace7f3df'
down_revision: Union[str, Sequence[str], None] = '1ef207923052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('topic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'topic')
    # ### end Alembic commands ###
